<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title><![CDATA[Category: fedora.planet | atodorov.org - you can logoff, but you can never leave]]></title>
  <link href="http://atodorov.org/blog/categories/fedora-planet/atom.xml" rel="self"/>
  <link href="http://atodorov.org/"/>
  <updated>2015-11-24T22:05:37+02:00</updated>
  <id>http://atodorov.org/</id>
  <author>
    <name><![CDATA[Alexander Todorov]]></name>
    
  </author>
  <generator uri="http://octopress.org/">Octopress</generator>

  
  <entry>
    <title type="html"><![CDATA[python-libs in RHEL 7.2 broke SSL verification in s3cmd]]></title>
    <link href="http://atodorov.org/blog/2015/11/24/python-libs-in-rhel-7.2-broke-ssl-verification-in-s3cmd/"/>
    <updated>2015-11-24T21:44:00+02:00</updated>
    <id>http://atodorov.org/blog/2015/11/24/python-libs-in-rhel-7.2-broke-ssl-verification-in-s3cmd</id>
    <content type="html"><![CDATA[<p>Today started with <a href="http://planet.sofiavalley.com">Planet Sofia Valley</a> being
broken again. Indeed it's been broken since last Friday when I've upgraded to
the latest RHEL 7.2. I quickly identified that I was hitting
<a href="https://github.com/s3tools/s3cmd/issues/647">Issue #647</a>. Then I tried the
git checkout without any luck. This is when I started to suspect that python-libs
has been updated in an incompatible way.</p>

<p>After series of reported bugs,
<a href="https://bugzilla.redhat.com/show_bug.cgi?id=1284916">rhbz#1284916</a>,
<a href="https://bugzilla.redhat.com/show_bug.cgi?id=1284930">rhbz#1284930</a>,
<a href="http://bugs.python.org/issue25722">Python#25722</a>, it was clear that
<code>ssl.py</code> was working according to RFC6125, that Amazon S3 was not playing
nicely with this same RFC and that my patch proposal was wrong.
This immediately had me looking upper in the stack at <code>httplib.py</code> and <code>s3cmd</code>.</p>

<p>Indeed there was a change in <code>httplib.py</code> which introduced two parameters,
<em>context</em> and <em>check_hostname</em>, to <code>HTTPSConnection.__init__</code>. The change
also supplied the logic which performs SSL hostname validation.</p>

<pre><code>if not self._context.check_hostname and self._check_hostname:
    try:
        ssl.match_hostname(self.sock.getpeercert(), server_hostname)
    except Exception:
        self.sock.shutdown(socket.SHUT_RDWR)
        self.sock.close()
        raise
</code></pre>

<p>This looks a bit doggy as I don't quite understand the intention behind
<em>not PREDICATE and PREDICATE</em>. Anyway to disable the validation you need
both parameters set to False, which is
<a href="https://github.com/s3tools/s3cmd/pull/668">PR #668</a>.</p>

<p>Notice the two try-except blocks. This is in case we're running with a
version that has a context but not the check_hostname parameter. I've found
the <em>inspect.getmembers</em> function which can be used to figure out what
parameters are there for the init method but a solution based on it
doesn't appear to be more elegant. I will describe this in more details in
my next post.</p>
]]></content>
  </entry>
  
  <entry>
    <title type="html"><![CDATA[GitHub Bugzilla Hook]]></title>
    <link href="http://atodorov.org/blog/2015/11/24/github-bugzilla-hook/"/>
    <updated>2015-11-24T13:32:00+02:00</updated>
    <id>http://atodorov.org/blog/2015/11/24/github-bugzilla-hook</id>
    <content type="html"><![CDATA[<p>Last month I've created a tool which adds comments to Bugzilla when a commit
message references a bug number. It was done as a proof of concept and didn't
receive much attention at the time. Today I'm happy to announce the existence
of <a href="https://github.com/atodorov/github-bugzilla-hook">GitHub Bugzilla Hook</a>.</p>

<p>I've used David Shea's
<a href="https://github.com/rhinstaller/github-email-hook/">GitHub Email Hook</a> as my
starting template and only modified it where needed. GitHub Bugzilla Hook will
examine push data and post comments for every unique bug+branch combination.
Once a comment for that particular bug+branch combination is made, new ones
will not be posted, even if later commits reference the same bug.
My main assumption is commits which are related to a bug will be pushed together
most of the times so there shouldn't be lots of noise in Bugzilla.</p>

<p>See <a href="https://bugzilla.redhat.com/show_bug.cgi?id=1274703">rhbz#1274703</a> for
example of how the comments look. The parser behavior is taken from anaconda
and conforms to the style the Red Hat Installer Engineering Team uses.
Hopefully you find it useful as well.</p>

<p>My next step is to find a hosting place for this script and hook it up
with the rhinstaller GitHub repos!</p>
]]></content>
  </entry>
  
  <entry>
    <title type="html"><![CDATA[Bad Stub Design in DNF, Pt.2 ]]></title>
    <link href="http://atodorov.org/blog/2015/11/23/bad-stub-design-in-dnf/"/>
    <updated>2015-11-23T15:55:00+02:00</updated>
    <id>http://atodorov.org/blog/2015/11/23/bad-stub-design-in-dnf</id>
    <content type="html"><![CDATA[<p>Do you remember my example of a
<a href="/blog/2015/09/25/unit-testing-bad-stub-design-in-dnf/">bad stub design in DNF</a> ?
At that time I didn't have a good example of why this is a bad design and what are the
consequences of it. Today I have!</p>

<p>From my comment on
<a href="https://github.com/rpm-software-management/dnf-plugins-core/pull/118">PR #118</a>
<blockquote><p>Note: the benefit of this patch are quite subtle.<br/>I've played around with creating a few more tests and the benefit I see affect<br/>only a few lines of code.</p></p><p><p>For #114 there doesn't seem to be any need to test _get_query directly,<br/>although we call<br/>```</p></p><p><pre><code>   q = self.base.sack.query()<br/>   q = q.available()<br/></code></pre></p><p><p>```</p></p><p><p>which will benefit from this PR b/c we're stubbing out the entire Sack object.<br/>I will work on a test later today/tomorrow to see how it looks.</p></p><p><p>OTOH for #113 where we modify _get_query the test can look something like this:</p></p><p><p>```</p></p><p><pre><code>def test_get_query_with_local_rpm(self):<br/>    try:<br/>        (fs, rpm_path) = tempfile.mkstemp('foobar-99.99-1.x86_64.rpm')<br/>        # b/c self.cmd.cli.base is a mock object add_remote_rpm<br/>        # will not update the available packages while testing.<br/>        # it is expected to hit an exception<br/>        with self.assertRaises(dnf.exceptions.PackageNotFoundError):<br/>            self.cmd._get_query(rpm_path)<br/>        self.cmd.cli.base.add_remote_rpm.assert_called_with(rpm_path)<br/>    finally:<br/>        os.remove(rpm_path)<br/></code></pre></p><p><p>```</p></p><p><p>Note the comment above the with block. If we leave out <code>_get_query</code> as before<br/>(a simple stub function) we're not going to be able to use <code>assert_called_with</code><br/>later.</p></blockquote></p>

<p>Now a more practical example. See
<a href="https://github.com/rpm-software-management/dnf-plugins-core/commit/fe130669ffc4c1d6eba8f10cda35ab4d803d5a3d">commit fe13066</a>
- in case the package is not found we log the error. In case configuration is
<code>strict=True</code> then the plugin will raise another exception. With the initial version
of the stubs this change in behavior is silently ignored. If there was an error
in the newly introduced lines it would go straight into production because the
existing tests passed.</p>

<p>What happens is that <code>test_get_packages()</code> calls <code>_get_packages(['notfound'])</code>,
which is not the real code but a test stub and returns an empty list in this case.
The empty list is expected from the test and it will not fail!</p>

<p>With my new stub design the test will execute the actual <code>_get_packages()</code>
method from <code>download.py</code> and choke on the exception. The test itself needs
to be modified, which is done in
<a href="https://github.com/atodorov/dnf-plugins-core/commit/2c2b34237c99cbf32e23bde43027d22873f4e8b7">commit 2c2b34</a>
and no further errors were found.</p>

<p>So let me summarize:
<strong>
When using mocks, stubs and fake objects we should be replacing external
dependencies of the software under test, not internal methods from the SUT!
</strong></p>
]]></content>
  </entry>
  
  <entry>
    <title type="html"><![CDATA[Tip: Running DNF Plugins from git]]></title>
    <link href="http://atodorov.org/blog/2015/11/23/tip-running-dnf-plugins-from-git/"/>
    <updated>2015-11-23T15:50:00+02:00</updated>
    <id>http://atodorov.org/blog/2015/11/23/tip-running-dnf-plugins-from-git</id>
    <content type="html"><![CDATA[<p>This is mostly for self reference because it is not currently documented
in the code. To use dnf plugins from a local git checkout modify your
<code>/etc/dnf/dnf.conf</code> and add the following line under the <code>[main]</code> section:</p>

<pre><code>pluginpath=/path/to/dnf-plugins-core/plugins
</code></pre>
]]></content>
  </entry>
  
  <entry>
    <title type="html"><![CDATA[Updated MacBook Air Drivers for RHEL 7.2]]></title>
    <link href="http://atodorov.org/blog/2015/11/21/updated-macbook-air-drivers-for-rhel-7.2/"/>
    <updated>2015-11-21T11:27:00+02:00</updated>
    <id>http://atodorov.org/blog/2015/11/21/updated-macbook-air-drivers-for-rhel-7.2</id>
    <content type="html"><![CDATA[<p>Yesterday I've upgraded to
<a href="https://access.redhat.com/announcements/2058583">Red Hat Enterprise Linux 7.2</a>
on my MacBook Air and I decided to rebuild the wifi and backlight drivers.
Wifi broke immediately but I was able to fix the build with a
<a href="https://github.com/atodorov/wl-kmod-for-rhel7/commit/88d678a25eb702ce36f7c39471edefb65de57ad5">simple patch</a>.
I'm now using the newly built <em>kmod-wl-3.10.0-327.el7.x86_64-6.30.223.248-7.el7.x86_64</em>
and it appears to work as expected.</p>

<p>The <em>mba6x_bl</em> driver built without problems however I'm having problems when
closing the laptop lid. The screen stays on and (I think) the computer doesn't
suspend. My battery was drained as I left the computer as-is overnight. Suspending
from the Desktop menu however appears to work. See
<a href="https://github.com/patjak/mba6x_bl/issues/41">Issue #41</a>. I'd love to get some
help in debugging what's going wrong and trying to fix it. At this point I have
no idea where to look and if it's the driver to blame or something else on the system.</p>
]]></content>
  </entry>
  
</feed>
